// adminTableData.jsx

// Define columns for the table
export const columns = [
  { id: 'transactionId', label: 'Transaction ID', minWidth: 100 },
  { id: 'transactionDate', label: 'Transaction Date', minWidth: 170 },
  { id: 'senderID', label: 'Sender ID', minWidth: 100 },
  { id: 'senderName', label: 'Sender Name', minWidth: 150 },
  { id: 'receiverID', label: 'Receiver ID', minWidth: 100 },
  { id: 'receiverName', label: 'Receiver Name', minWidth: 150 },
  { id: 'amount', label: 'Amount', minWidth: 100, format: (value) => value.toLocaleString('en-US') },
  { id: 'transactionStatus', label: 'Status', minWidth: 100 },
  { id: 'transactionType', label: 'Type', minWidth: 100 },
];

// Define rows for the table (sample data)
export const rows = [
  {
    transactionId: 1,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 2,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 3,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 4,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 5,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 6,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 7,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 8,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 9,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 10,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 11,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 12,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 13,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 14,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 15,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 16,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 17,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 18,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  {
    transactionId: 19,
    transactionDate: '2023-07-01',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 500,
    transactionStatus: 'Pending',
    transactionType: 'Withdrawal',
  },
  {
    transactionId: 20,
    transactionDate: '2023-07-02',
    senderID: '00632543',
    senderName: 'Brandon Wee',
    receiverID: '00633754',
    receiverName: 'John Doe',
    amount: 700,
    transactionStatus: 'Successful',
    transactionType: 'Deposit',
  },
  // Add more rows as needed
];
